In [2]:
import numpy as np
va=np.array([1,2,3,4,5,6])
add=va+4
print(add)

[ 5  6  7  8  9 10]


In [4]:
import numpy as np
va=np.array([1,2,3,4,5,6])
add=va+45
sub=va-6
mul=va*4
div=va/9
print(add)
print(sub)
print(mul)
print(div)

[46 47 48 49 50 51]
[-5 -4 -3 -2 -1  0]
[ 4  8 12 16 20 24]
[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667]


Arihtmetic operation using functions

In [7]:
v=np.array([2,4,5,6,7,8,9])
v1=np.multiply(v,3)
v2=v*3
v3=v**3
print(v1)
print(v2)
print(v3)

[ 6 12 15 18 21 24 27]
[ 6 12 15 18 21 24 27]
[  8  64 125 216 343 512 729]


for 2d arrays

In [12]:
var=np.array([[1,2,3,4],[2,3,4,5]])
tar=np.array([[2,3,4,5],[9,8,7,6]])
print(var)
print("")
print(tar)
print("")
a=var+tar
print(a)
print("")
print(a.ndim)
print(tar.ndim)

[[1 2 3 4]
 [2 3 4 5]]

[[2 3 4 5]
 [9 8 7 6]]

[[ 3  5  7  9]
 [11 11 11 11]]

2
2


In [13]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
rec=np.reciprocal(a)
print(rec)

[1 0 0 0 0 0 0]


In [15]:
a=np.array([2,3,4,5,6])
print("Minimum:",np.min(a,np.argmin(a)))
print("Maximum:",np.max(a))

Minimum: 2
Maximum: 6


In [19]:
import numpy as np
var1=np.array([[1,2,43],[3,4,6]])
print(np.min(var1,axis=1))
print(np.argmin(var1))
print(np.argmax(var1))

[1 3]
0
2


In [10]:
import numpy as np
var1=np.array([[1,2,3],
               [2,3,4],
               [6,7,8]])
var2=np.array([[1,2,9],
               [2,3,2],
               [9,8,7]])

print("Matrix 1:\n",var1)
print()
print("Matrix 2:\n",var2)
print()
print("Addition values:\n")
v=np.add(var1,var2)
print(v)
print("Substracted values:\n")
var4=np.subtract(var1,var2)
var5=var1*var2
var5=var1/var2
var6=var1**var2
var7=np.sqrt(var2)

print()
print("Multiplied values:\n",var5)
print()
print("Exponential values:\n",var6)
print()
print("Square root values:\n",var7)

print("Shapre of the matrix:")
print(np.shape(var7))

print("Sine values of the matrix numbers:\n")
print(np.sin(var7))
print("")
print("Cosine values of the exponential values:\n")
print(np.cos(var6))
print("Tangent values of the differential matrix:\n")
print(np.tan(var4))

Matrix 1:
 [[1 2 3]
 [2 3 4]
 [6 7 8]]

Matrix 2:
 [[1 2 9]
 [2 3 2]
 [9 8 7]]

Addition values:

[[ 2  4 12]
 [ 4  6  6]
 [15 15 15]]
Substracted values:


Multiplied values:
 [[1.         1.         0.33333333]
 [1.         1.         2.        ]
 [0.66666667 0.875      1.14285714]]

Exponential values:
 [[       1        4    19683]
 [       4       27       16]
 [10077696  5764801  2097152]]

Square root values:
 [[1.         1.41421356 3.        ]
 [1.41421356 1.73205081 1.41421356]
 [3.         2.82842712 2.64575131]]
Shapre of the matrix:
(3, 3)
Sine values of the matrix numbers:

[[0.84147098 0.98776595 0.14112001]
 [0.98776595 0.98702664 0.98776595]
 [0.14112001 0.30807174 0.47577184]]

Cosine values of the exponential values:

[[ 0.54030231 -0.65364362 -0.60420762]
 [-0.65364362 -0.29213881 -0.95765948]
 [ 0.66892472 -0.89074651  0.78154857]]
Tangent values of the differential matrix:

[[ 0.          0.          0.29100619]
 [ 0.          0.         -2.18503986]
 [ 0.14254654

In [ ]:
import numpy as np
var1=np.array([[1,2,3],
               [2,3,4],
               [6,7,8]])
var2=np.array([[1,2,9],
               [2,3,2],
               [9,8,7]])

print("Matrix 1:\n",var1)
print()
print("Matrix 2:\n",var2)
print()
v=np.add(var1,var2)
print(v)

var4=np.subtract(var1,var2)
var5=var1*var2
var5=var1/var2
var6=var1**var2
var7=np.sqrt(var2)

print()
print("Difference:\n",var4)
print()
print("Multiply:\n",var5)
print()
print("Exponent:\n",var6)
print()
print("Square root:\n",var7)

print(np.shape(var7))



To find maximum and minimum element using numpy library


In [13]:
import numpy as np
var=np.array([1,3,5,7,9])
print("Maximum value:", np.max(var))
print("Minimum value:" , np.min(var))
print("Maximum value indeX:" , np.argmax(var))
print("Minimum value index:" , np.argmin(var))

Maximum value: 9
Minimum value: 1
Maximum value indeX: 4
Minimum value index: 0


In [18]:
var=([[1,2,3],[5,6,7]])
print("Minimum value column wise:",np.min(var , axis=0))
print("Maximum value row wise:",np.max(var,axis=1))
print("Square root values of matrix:\n",np.sqrt(var))
a=5
print("Square root of 5:")
print(np.sqrt(a))

Minimum value column wise: [1 2 3]
Maximum value row wise: [3 7]
Square root values of matrix:
 [[1.         1.41421356 1.73205081]
 [2.23606798 2.44948974 2.64575131]]
Square root of 5:
2.23606797749979


Cumsum means sumamtion of the current values with all the previous values

In [21]:
car=np.array([12,33,555])
print("Sine values->")
print(np.sin(car))
print("Cosine values->")
print(np.cos(car))
print("Tangential values->")
print(np.tan(car))
print("Cumsum->" , np.cumsum(car))

Sine values->
[-0.53657292  0.99991186  0.87328261]
Cosine values->
[ 0.84385396 -0.01327675 -0.487214  ]
Tangential values->
[ -0.63585993 -75.3130148   -1.79240049]
Cumsum-> [ 12  45 600]
