Indexing and slicing in numpy array

In [7]:
import numpy as np
nums=np.array([2,3,45,9,5])
print("Second element:",nums[2])
print('First element:',nums[0])
len1=len(nums)
print("Last element:",nums[len1-1])

Second element: 45
First element: 2
Last element: 5


In [14]:
var1=np.array([[1,2,3],[8,7,6]])
print(var1)
print("Dimension:",np.ndim(var1))

print(var1[0,2])

[[1 2 3]
 [8 7 6]]
Dimension: 2
3


In [24]:
import numpy as np
var=np.array([[[1,2],[5,6],[7,6]]])
print("3 dimensional Array:")
print(var)
print("Dimension of the array:",np.ndim(var))

# to get  number array
print(var[0,2])
print()
print(var[0,1])

3 dimensional Array:
[[[1 2]
  [5 6]
  [7 6]]]
Dimension of the array: 3
[7 6]

[5 6]


In [34]:
var=np.array([4,3,2,3,3,4,5,5,76,7,5,5,5])
e=len(var)
print(var[0:e])
print(var)
print(var[0:e:2])
print(var[3:e:3])
print(var[3:])
print(var[:5])

[ 4  3  2  3  3  4  5  5 76  7  5  5  5]
[ 4  3  2  3  3  4  5  5 76  7  5  5  5]
[ 4  2  3  5 76  5  5]
[3 5 7 5]
[ 3  3  4  5  5 76  7  5  5  5]
[4 3 2 3 3]


In [40]:

var=np.array([2,3,5,5,6,7])
print(var)
e=len(var)
print(var[0:e:3])


[2 3 5 5 6 7]
[2 5]


for 2D arrays

In [51]:
import numpy as np
car=np.array([[1,2,3],[5,6,87],[5,6,7]])
e=len(car)
print()
print("0th index value:",car[0])
print("1st index value:",var[1])
print("2nd index array:" ,var[2])
print('Length of the matrix:',e)
print("Sliced array:",car[0:e:3])
print("Dimension of the array:",np.ndim(car))


0th index value: [1 2 3]
1st index value: 3
2nd index array: 5
Length of the matrix: 3
Sliced array: [[1 2 3]]
Dimension of the array: 2
