To implement insert and deletion in array(numpy wala)

In [4]:
import numpy as np 
a=np.array([2,3,4,5,67])
print(a)
print(type(a))
print("Dimension->",np.ndim(a))
x=np.insert(a,3,100)
#          (array,postion,value)
print("After value insertion->",x)

[ 2  3  4  5 67]
<class 'numpy.ndarray'>
Dimension-> 1
After value insertion-> [  2   3   4 100   5  67]


for 1-d dimensional array

In [5]:
import numpy as np
var1=np.array([2,3,4,5,4,3,4,3])
print(var1)
x=np.insert(var1,len(var1),1000)
print(x)
print("Thank you.")

[2 3 4 5 4 3 4 3]
[   2    3    4    5    4    3    4    3 1000]


In [10]:
import numpy as np
var=np.array([2,3,4,45,5,5,5,4,3])
print("Original->",var)
v=np.insert(var,3,-4,axis=0)
print("Modified->", v)
b=np.insert(var,4,-2,axis=0)
print("Modified again->" , b)
c=np.insert(var,2,[3,4,5,6,7])
print("Modified->", c)

Original-> [ 2  3  4 45  5  5  5  4  3]
Modified-> [ 2  3  4 -4 45  5  5  5  4  3]
Modified again-> [ 2  3  4 45 -2  5  5  5  4  3]
[ 2  3  3  4  5  6  7  4 45  5  5  5  4  3]


Two dimensional implementation

In [14]:
import numpy as np
a=np.array([[1,2,3],[56,6,7],[2,3,4]])
print(a)
x=np.insert(a,3,[4,3,2],axis=1)
print("Modified matrix:")
print(x)

[[ 1  2  3]
 [56  6  7]
 [ 2  3  4]]
Modified matrix:
[[ 1  2  3  4]
 [56  6  7  3]
 [ 2  3  4  2]]


Deletion operation

In [23]:
import numpy as np
var1=np.array([3,4,56,7])
print("Orginal list->" , var1)
index=int(input("Enter the index you want to delete:"))
d=np.delete(var1,index)
print("After deletation->" , d)
i=int(input("Enter the value of the index you want to delete again:"))
v=np.delete(d,i)
print("After deletation->" , v)

Orginal list-> [ 3  4 56  7]
After deletation-> [ 3  4 56]
After deletation-> [3 4]
