To implement matrix operation

In [7]:
import numpy as np 
var=np.array([2,3,43,5,5,3,4,3,3])
print(var)
print("2d-lists->")
var1=np.array([[2,3],[7,8],[4,5]])
print(var1)
print("Dimension->" , np.ndim(var1))
print("Data type->" , type(var1))

[ 2  3 43  5  5  3  4  3  3]
2d-lists->
[[2 3]
 [7 8]
 [4 5]]
Dimension-> 2
Data type-> <class 'numpy.ndarray'>


In [8]:
import numpy as np
c=np.matrix([[3,4,5],[7,6,56],[3,4,5]])
print("Matrix->")
print(c)
print("Dimension->",np.ndim(c))
print("Datatype->", type(c))
print("Program is sucessful..thank you.")

Matrix->
[[ 3  4  5]
 [ 7  6 56]
 [ 3  4  5]]
Dimension-> 2
Datatype-> <class 'numpy.matrix'>
Program is sucessful..thank you.


To perform matrix arithmetic operation

In [ ]:
import numpy as np
a=np.matrix([[2,3,4],[4,5,6]])
b=np.matrix([[2,3,4],[5,6,7]])
print("Sumation matrix->")
print((a+b))
print("Difference matrix->")
print(a-b)
print("Multiplication matrix->")
print(a*b)

print("Thank You ,have a nice day.")

In [16]:
import numpy as np
a=np.array([[2,3],[6,7]])
b=np.array([[1,2],[5,6]])

print(a+b)
print("")
print(a-b)
print("")
print(a*b)

[[ 3  5]
 [11 13]]

[[1 1]
 [1 1]]

[[ 2  6]
 [30 42]]


Common matrix operations::
->Transpose
->Swapaxes
->Inverse
->Power
->Determinate

Transpose

In [26]:
import numpy as np
cv=np.matrix([[1,2],[5,6]])
c=np.matrix([[1,2,3],[6,7,8],[3,2,1]])
print("Normal matrix->",cv)
print("Transpose:", np.transpose(cv))
print("Orginal matrix->",c)
print("Transpose->\n" ,np.transpose(c))
print("After swapaxes function:")
print(np.swapaxes(c,0,1))

Normal matrix-> [[1 2]
 [5 6]]
Transpose: [[1 5]
 [2 6]]
Orginal matrix-> [[1 2 3]
 [6 7 8]
 [3 2 1]]
Transpose->
 [[1 6 3]
 [2 7 2]
 [3 8 1]]
After swapaxes function:
[[1 6 3]
 [2 7 2]
 [3 8 1]]


To find inverse of a matrix

In [29]:
import numpy as np
print("Original:")
var=np.matrix([[1,3,4],[7,6,45,],[3,4,5]])
print(var)
print()
print("Inverse->")
print(np.linalg.inv(var))
print("Determinant of the matrix:")
print(np.linalg.det(var))

Original:
[[ 1  3  4]
 [ 7  6 45]
 [ 3  4  5]]

Inverse->
[[-0.78947368  0.00526316  0.58421053]
 [ 0.52631579 -0.03684211 -0.08947368]
 [ 0.05263158  0.02631579 -0.07894737]]
Determinant of the matrix:
190.0


In [40]:
import numpy as np
var=np.matrix([[1,2],[5,65]])
print("Original matrix->")
print(var)
x=np.linalg.trace(var)
print("Trace of the matrix :")
print(x)
print("Exponential values:")
print(np.linalg.matrix_power(var, 2))
print("Rank of the matrix:")
print(np.linalg.matrix_rank(var))
print("Norm of the matrix:")
print(np.linalg.matrix_norm(var))
print("Transpose of the matrix:")
print(np.linalg.matrix_transpose(var))

Original matrix->
[[ 1  2]
 [ 5 65]]
Trace of the matrix :
66
Exponential values:
[[  11  132]
 [ 330 4235]]
Rank of the matrix:
2
Norm of the matrix:
65.23036102920173
Transpose of the matrix:
[[ 1  5]
 [ 2 65]]
