In [4]:
# demonstration of numpy.
import numpy as np
x=np.array([1,2,3])
print(x)

[1 2 3]


In [8]:
# input a data nd push it into a list.
l=[]
for i in range(1,5):
    my_data=int(input("Enter data of your choice:"))
    l.append(my_data)
print(np.array(l))

[ 7  9  5 12]


In [9]:
# demo numpy
import numpy as np
lis=[]
for i in range(1,3):
    lis.append(i)
print(lis)
print(np.array(list))
print(type(lis))

[1, 2]
<class 'list'>


In [11]:
import numpy as np
a=np.array([1,2,3,4])
print(type(a))
print("Dimension of the array:",a.ndim)

<class 'numpy.ndarray'>
Dimension of the array: 1


In [13]:
# demo of 2d array
import numpy as np
ar2=np.array([[1,2,3,4],[3,4,5,6]])
for element in ar2:
    print(element)
print("Dimension of the array->",ar2.ndim)

[1 2 3 4]
[3 4 5 6]
Dimension of the array-> 2


In [1]:
import numpy as np
ar3=np.array([[1,2],[4,5],[5,6]])
print(ar3)
print("Dimension of the array:",ar3.ndim)

[[1 2]
 [4 5]
 [5 6]]
Dimension of the array: 2


In [1]:
# 10 dimensional array
import numpy as np 
arn=np.array([1,2,3], ndmin=3)
print(arn)

[[[1 2 3]]]


In [8]:
# reshape in numpy
import numpy as np
var=np.array([1,2,3,4,5,6,7,8,9])
x=var.reshape(3,3)
print(x)
print()
print("Dimension:" , x.ndim)
print(x.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension: 2
2
