In [1]:
# to randomly shuffle an array
import numpy as np
var=np.array([5,4,3,2,43,3])
print(var)
np.random.shuffle(var)
print("Rearranged:")
print(var)


[ 5  4  3  2 43  3]
Rearranged:
[ 2  5  4 43  3  3]


In [6]:
# to remove duplicate elements
var1=np.array([3,4,4,3,4,5,5,5,5,5,6,7,8])
x=np.unique(var1,return_index=True,return_counts=True)
print(x)

(array([3, 4, 5, 6, 7, 8]), array([ 0,  1,  5, 10, 11, 12]), array([2, 3, 5, 1, 1, 1]))


In [2]:
#implement resize function
import numpy as np
v=np.array([2,3,4,5,6,7,7,7,8,5])
y=np.resize(v,(3,2))
print(y)


[[2 3]
 [4 5]
 [6 7]]


To implement flatten function in
numpy

In [6]:
import numpy as np
var=np.array([1,2,4,5,6,7,8,9,0])
r=np.resize(var,(3,2))
print(r)
print("Flatten->",r.flatten())
print("Ravel:" , np.ravel(r))

print("Dimension->",np.ndim(r))

[[1 2]
 [4 5]
 [6 7]]
Flatten-> [1 2 4 5 6 7]
Ravel: [1 2 4 5 6 7]
Dimension-> 2
