Numpy array iterating

In [6]:
import numpy as np
var=np.array([2,3,4,5])
print(var)
for i in range(0,len(var)):
    print(var[i],"\t")
print("Thank you.")

[2 3 4 5]
2 	
3 	
4 	
5 	
Thank you.


In [10]:
var=np.array([[1,2],[3,4],[8,9]])
print(var)
print("Dimension ->",np.ndim(var))

for i in var:
    print(i)
for k in var:
    for j in k:
        print(j)

[[1 2]
 [3 4]
 [8 9]]
Dimension -> 2
[1 2]
[3 4]
[8 9]
1
2
3
4
8
9


In [16]:
import numpy as np
arr=np.array([[[1,2],[4,5],[9,8]]])
print(arr)
print("Dimension ->",np.ndim(arr))
for i in arr:
    print(i)
#iterating a 3d array in different way
for j in arr:
    for k in j:
        for l in k:
            print(l)


[[[1 2]
  [4 5]
  [9 8]]]
Dimension -> 3
[[1 2]
 [4 5]
 [9 8]]
1
2
4
5
9
8


In [1]:
import numpy as np
va=np.array([[[1,2,3,4],[5,6,7,4]]])
print(va)
for i in np.nditer(va):
    print(i)


[[[1 2 3 4]
  [5 6 7 4]]]
1
2
3
4
5
6
7
4
