In [2]:
import numpy as np
var=np.array([1,2,3,4,5])
print("Data type:" , var.dtype)
print("Dimension:" , var.ndim)

Data type: int64
Dimension: 1


In [3]:
var=np.array([2.5,6.7,6.7])
print(var)
print("Data type:",var.dtype)
print("Dimension:" , var.ndim)

[2.5 6.7 6.7]
Data type: float64
Dimension: 1


In [5]:
var=np.array(["Apple","Pineapple",23,34])
print(var)
print("Data type:",var.dtype)
print("Dimension:", var.ndim)

['Apple' 'Pineapple' '23' '34']
Data type: <U21
Dimension: 1


In [12]:
x=np.array([1,2,3,4,5],dtype=np.int8)
print("Data type:",x.dtype)
print((x))

Data type: int8
[1 2 3 4 5]


In [14]:
x=np.array([1,2,3,4,5],dtype="f")
print("Data type:",x.dtype)
print((x))

Data type: float32
[1. 2. 3. 4. 5.]


In [19]:
x=np.array([1,2,3,4,5])
new=np.float32(x)
print(new)
print(x)
print("Data type:" , new.dtype)
print("Dimesion:" , new.ndim)

# in integer form
v=np.int32(new)
print("In integer form:",v)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
Data type: float32
Dimesion: 1
In integer form: [1 2 3 4 5]


In [23]:
x=np.array([1,2,3,4,5])
new=x.astype(float)
pl=np.float16(x)
print(x)
print(new)
print(pl)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]
