In [2]:
import numpy as np
arr=np.array([2,3,4,5,6,7])
print(arr)

element=5
if element in arr:
    print("Present")
else:
    print("Absent")


[2 3 4 5 6 7]
Present


In [6]:
import numpy as np
var=np.array([1,2,3,4,2,354,2,5,4,5,2,8])
x=np.where(var == 2)
print("Positions->" , x)
print(np.sort(var))

Positions-> (array([ 1,  4,  6, 10]),)
[  1   2   2   2   2   3   4   4   5   5   8 354]


Matrix

In [2]:
import numpy as np
arr=([[1,3],[5,4],[3,4]])
print(arr)
x=np.sort((arr),axis=1)
print(x)

[[1, 3], [5, 4], [3, 4]]
[[1 3]
 [4 5]
 [3 4]]


print only those elements which are prent in even index

In [3]:
import numpy as np
var=np.array([1,2,3,4,45,56,6])
x=np.where((var%2)==0)
print(x)

(array([1, 3, 5, 6]),)


Search sorted array

In [8]:
#performs binary search where the element in array will be placed.
import numpy as np
var=np.array([1,2,3,4,45,6])
x1=np.searchsorted(var,[9,-8,17],side="right")
print(x1)

[6 0 6]


Sort array

In [11]:
import numpy as np
var=np.array([4,3,2,5,6])
print(var)
x=np.sort(var)
print('Sorted:')
print(x)

[4 3 2 5 6]
[2 3 4 5 6]


For alphabets i.e. for string character

In [12]:
import numpy as np
car=np.array(["e","u","a"])
c=np.sort(car)
print(c)

['a' 'e' 'u']


For 2d arrays

In [15]:
import numpy as np
var1=np.array([[3,4],[6,7],[2,3]])
print("Normal array:")
print(var1)
x=np.sort((var1))
print(x)

Normal array:
[[3 4]
 [6 7]
 [2 3]]
[[3 4]
 [6 7]
 [2 3]]


Filter array

In [17]:
import numpy as np
arr=np.array([3,4,7,8])
f=[True,False,True,False]
new=arr[f]
print(new)
print("Type->" , type(new))

[3 7]
Type-> <class 'numpy.ndarray'>
