In [1]:
#shape
import numpy as np
var=np.array([[13,4],[3,4]])
print("Array:")
print(var)
print("Shape:" , np.shape)
print("Islamic emirate of afghanistan")
print("Dimension:" , np.ndim)

Array:
[[13  4]
 [ 3  4]]
Shape: <function shape at 0x000002E835282160>
Islamic emirate of afghanistan
Dimension: <function ndim at 0x000002E8352834C0>


In [24]:
var1=np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.shape)



[[[[1 2 3 4]]]]
(1, 1, 1, 4)


To reshape arrays

In [3]:
import numpy as np
var=np.array([1,2,3,4,5,76,6,8])
print(var)

s1=var.shape
s2=var.reshape(2,2,2)
print("Shape:" , s1)
print(s2)
print(s2.ndim)

one=s2.reshape(-1)
print(one)

[ 1  2  3  4  5 76  6  8]
Shape: (8,)
[[[ 1  2]
  [ 3  4]]

 [[ 5 76]
  [ 6  8]]]
3
[ 1  2  3  4  5 76  6  8]
