In [3]:
#Zero array
import numpy as np
at_zero=np.zeros(4)
at_zero1=np.zeros((3,4))
print(at_zero)
print(" ")
print(at_zero1)

[0. 0. 0. 0.]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#Ones array
import numpy as np
at_one=np.ones(3)
print(at_one)
at_one1=np.ones((4,4))
print(at_one1)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
#Empty array
import numpy as np
ar_emp=np.empty(4)
ar_empd=np.empty((2,2))
print(ar_emp)

print(ar_empd)

[7.56572645e-307 1.60220393e-306 9.79111946e-307 2.41910791e-312]
[[ 6.95312981e-310  6.95312981e-310]
 [ 6.54902186e-223 -8.44612125e+252]]


In [16]:
#Range
import numpy as np
arr=np.arange(28)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [3]:
#diagonal element
import numpy as np
arr=np.eye(2,7) # for diagonal element.
print(arr)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]


In [5]:
#linespace
import numpy as np
arr_lin=np.linspace(7,35,num=7)
print(arr_lin)

[ 7.         11.66666667 16.33333333 21.         25.66666667 30.33333333
 35.        ]


Exploring numpy as an imposter

In [9]:
# create numpy array from random 
import numpy as np
a=np.random.rand(2)
print(a)

[0.70726857 0.50096875]


In [12]:
var1=np.random.rand(3,3)
print(var1)

[[0.32310372 0.39333727 0.37632711]
 [0.89882429 0.78389559 0.96213774]
 [0.13112235 0.09495542 0.92692033]]


In [13]:
#randn() func.to generate  rnadom +ve and -ve numbers.
var2=np.random.randn(3,3)
print(var2)

[[ 0.62457759 -1.0466597  -1.61412527]
 [ 0.67714295  0.37350241  0.44347902]
 [ 1.33807387 -0.35302036  1.52616853]]


In [15]:
# to generate random floating values.
var3=np.random.ranf(4)
print(var3)

[0.94095171 0.19537051 0.55566413 0.18471633]


In [18]:
# to generate random int numbers within a range.
var=np.random.randint(4,5,7)
#min value=4,max value =5,generate random 7 numbers.
print(var)

[4 4 4 4 4 4 4]
